version: "3.8"
services:
  redis:
    image: "redis:alpine"
    container_name: chatbot-redis
    ports:
      - "6379:6379"
    volumes:
      - chatbot_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  qdrant:
    image: "qdrant/qdrant"
    container_name: chatbot-qdrant
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc

    volumes:
      - chatbot_qdrant_data:/qdrant/storage # Persist data in the Docker volume
    restart: always

volumes:
  chatbot_redis_data:
  chatbot_qdrant_data:
